Add plugin-check page
ebanx-integration/ebanx-opencart pull request #4
Opened 2019-02-20 12:51 UTC by afstarosta

2019-02-20 12:51 UTC, afstarosta commented
`index.php?route=payment/ebanx_plugincheck`

2019-02-22 12:51 UTC, Ruanito requested changes

2019-02-22 12:51 UTC, Ruanito commented on catalog/controller/payment/ebanx_plugincheck.php
> +	const EBANX_VERSION = '2.4.0';
It's better call `PLUGIN_VERSION` and set as private

2019-02-22 12:51 UTC, Ruanito commented on catalog/controller/payment/ebanx_plugincheck.php
> +			'mysql'          => $this->getSQLVersion(),
Open cart only use mysql?

2019-02-22 12:51 UTC, Ruanito commented on catalog/controller/payment/ebanx_plugincheck.php
> +		if(!is_null($this->config->get('ebanx_express_mode'))){
You should create a function to validated if config is null
```suggestion
                if (self::isEbanxExpressMode()) 
```
```
private static function isEbanxExpressMode() {
		    return !is_null($this->config->get('ebanx_express_mode'));
}
```

2019-02-22 12:51 UTC, Ruanito commented on catalog/controller/payment/ebanx_plugincheck.php
> +		if(!is_null($this->config->get('ebanx_mode'))){
You should use  a function here too

2019-02-22 12:51 UTC, Ruanito commented on catalog/controller/payment/ebanx_plugincheck.php
> +			$configs['ebanx_express'] = array(
You should use a function just to return the array with ebanx_express array

2019-02-22 12:51 UTC, Ruanito commented on catalog/controller/payment/ebanx_plugincheck.php
> +			$configs['ebanx'] = array(
You should create a function to return a ebanx config

2019-02-22 17:48 UTC, Ruanito approved these changes

2019-02-22 17:48 UTC, merged